# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "wv-vc-state"
    dynamodb_table = "wv-tfstate-lock"
    key            = "terraform.tfstate"
    region         = "us-east-1"
  }
}
